services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: healthy
      POSTGRES_USER: healthy_user
      POSTGRES_PASSWORD: healthy_pass

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/healthy
      SPRING_DATASOURCE_USERNAME: healthy_user
      SPRING_DATASOURCE_PASSWORD: healthy_pass
